import { Geist, Geist_Mono, Merienda, Unbounded } from "next/font/google";
import "./globals.css";
import Header from "./components/Header/Header";
import Footer from "./components/Footer/Footer";
import { Providers } from "@/redux/Providers";
import ServiceFeatures from "./homeComponents/ServiceFeatures";
import AosInit from "./components/AosInit";
import ResponsiveToaster from "@/ResponsiveToaster";

const unbounded = Unbounded({
  variable: "--font-unbounded",
  subsets: ["latin"],
  display: "swap",
});
const merienda = Merienda({
  variable: "--font-merienda",
  subsets: ["latin"],
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${unbounded.variable} ${merienda.variable} antialiased`}
      >
        <Providers>
          <ResponsiveToaster></ResponsiveToaster>

          <AosInit></AosInit>

          <Header></Header>
          {children}
          <ServiceFeatures></ServiceFeatures>
          <Footer></Footer>
        </Providers>
      </body>
    </html>
  );
}
